name: Deploy Nginx to Minikube

on:
  workflow_dispatch:  # Trigger manually

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create kubeconfig file from secret
        run: |
          echo "$KUBECONFIG_MINIKUBE" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Show cluster info (debug)
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl cluster-info

      - name: Deploy nginx
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl apply -f - <<EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                  - containerPort: 80
          EOF

